"""added parsed map

Revision ID: 0ad510773e1e
Revises: 14aea2eb1b57
Create Date: 2025-11-20 00:31:14.952773

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ad510773e1e"
down_revision = "14aea2eb1b57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site_file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parsed_map", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site_file", schema=None) as batch_op:
        batch_op.drop_column("parsed_map")

    # ### end Alembic commands ###
