"""added annotation table

Revision ID: 14aea2eb1b57
Revises: 3a51d3c2ab85
Create Date: 2025-11-17 22:54:59.308779

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14aea2eb1b57"
down_revision = "3a51d3c2ab85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_annotation",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("annotation", sa.String(length=1000), nullable=False),
        sa.Column("function_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["site_file.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["site_user.public_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_annotation")
    # ### end Alembic commands ###
