"""add LicenseKey model

Revision ID: 169e8e5559a4
Revises: 4ff15f8f4b4d
Create Date: 2025-10-27 22:30:24.783599

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "169e8e5559a4"
down_revision = "4ff15f8f4b4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_license_key",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_license_key")
    # ### end Alembic commands ###
