"""add file model

Revision ID: 20ea08109622
Revises: 3a51d3c2ab85
Create Date: 2025-11-02 22:39:18.435715

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20ea08109622"
down_revision = "3a51d3c2ab85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # adjusted
    op.drop_table("site_file")
    op.create_table(
        "site_file",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("item_name", sa.String(length=100), unique=True, nullable=False),
        sa.Column("file_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["site_user.public_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # adjusted
    op.drop_table("site_file")
    op.create_table(
        "site_file",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=False),
        sa.Column("file_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["site_user.public_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###
