"""add file model

Revision ID: 3a51d3c2ab85
Revises: c0de04c8f459
Create Date: 2025-11-02 21:21:46.812563

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a51d3c2ab85"
down_revision = "c0de04c8f459"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_file",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=False),
        sa.Column("file_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["site_user.public_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_table("site-file")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site-file",
        sa.Column("uuid", sa.VARCHAR(length=36), nullable=False),
        sa.Column("item_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("owner_id", sa.VARCHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["site_user.public_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_table("site_file")
    # ### end Alembic commands ###
